### ISSUE TITLE
v2converter.ahk has errors

### ISSUE THREAD

**Issue by user1823** [mmikeww/AHK-v2-script-converter#171]
When trying to run v2converter.ahk, the following errors are shown

```
Error: This variable has not been assigned a value.

Specifically: global gQuotedStrings

	---- C:\Users\User\Downloads\AHK-v2-script-converter-master\ConvertFuncs.ahk
	3745: While (pos  := RegExMatch(srcStr, pattern, &m, pos+1))
	3745: {
▶	3746: gQuotedStrings.push(m[])
```

```
Error: This variable has not been assigned a value.

Specifically: local tag

	---- C:\Users\User\Downloads\AHK-v2-script-converter-master\ConvertFuncs.ahk
	3746: gQuotedStrings.push(m[])
	3747: tag := pref . gQuotedStrings.Length . trail
▶	3748: srcStr := StrReplace(srcStr, m[], tag,,, 1)
```

**Comment by Banaanae** [comment]
Can you send the script you were converting and the command line arguments (if any)?

**Comment by user1823** [comment]
> Can you send the script you were converting

I just reproduced it with the script mentioned in https://github.com/mmikeww/AHK-v2-script-converter/issues/170#issuecomment-2100297133.

> the command line arguments (if any)

I just double-clicked the v2convertor.ahk file and selected a .ahk file from the Browse window to convert. So, I don't think that there is any command line argument involved.

**Comment by andymbody** [comment]
This needs to be added to the top of v2converter.ahk

global gQuotedStrings

**Comment by andymbody** [comment]
This global declaration also needs to be added to the top of v2converter.ahk

in ;VARIABLES: section
global gQuotedStrings

**Comment by andymbody** [comment]
This global declaration also needs to be added to the top of v2converter.ahk

in ;VARIABLES: section
global gQuotedStrings

I'm still not up to speed with github, so will not be submitting a PR for this any time soon. But this should fix the error.

**Comment by andymbody** [comment]
This global declaration also needs to be added to the top of v2converter.ahk

in ;VARIABLES: section (around line 35 or so)
global gQuotedStrings := []

I'm still not up to speed with github, so will not be submitting a PR for this any time soon. But this should fix the error.

**Comment by andymbody** [comment]
To fix...

This global declaration also needs to be added to the top of v2converter.ahk

in ;VARIABLES: section (around line 35 or so)
global gQuotedStrings := []

I'm still not up to speed with github, so will not be submitting a PR for this any time soon.

**Comment by andymbody** [comment]
To fix... add the following global declaration to the ;VARIABLES: section of v2converter.ahk (around line 35 or so)

global gQuotedStrings := []

I'm still not up to speed with github, so will not be submitting a PR for this any time soon. Perhaps you can add this on your next edit Banaanae ?

**Comment by Banaanae** [comment]
Is it possible to fix this without editing `v2converter.ahk`?
Ideally all conversion logic should stay to `ConvertFuncs.ahk`, aside from the `Convert()` function

**Comment by andymbody** [comment]
> Is it possible to fix this without editing `v2converter.ahk`? Ideally all conversion logic should stay to `ConvertFuncs.ahk`, aside from the `Convert()` function

Could place the declaration in one of these, since these are includes within v2converter.ahk.

{ ;INCLUDES:
#Include lib/ClassOrderedMap.ahk
#Include Convert/1Commands.ahk
#Include Convert/2Functions.ahk
#Include Convert/3Methods.ahk
#Include Convert/4ArrayMethods.ahk
#Include Convert/5Keywords.ahk

OR add the following include to the list above in v2converter.ahk. Since the declaration is already included within ConvertFuncs.ahk (probably best idea).

#Include ConvertFuncs.ahk

**Comment by andymbody** [comment]
> Is it possible to fix this without editing `v2converter.ahk`? Ideally all conversion logic should stay to `ConvertFuncs.ahk`, aside from the `Convert()` function

Better idea would be to add the following include to the list below in v2converter.ahk. Since the global declaration is already included within ConvertFuncs.ahk. This would allow any future Globals to be placed in ConvertFuncs.ahk as well, with no further edits to v2converter.ahk.

#Include ConvertFuncs.ahk

{ ;INCLUDES:
#Include lib/ClassOrderedMap.ahk
#Include Convert/1Commands.ahk
#Include Convert/2Functions.ahk
#Include Convert/3Methods.ahk
#Include Convert/4ArrayMethods.ahk
#Include Convert/5Keywords.ahk

**Comment by andymbody** [comment]
Looks like I was wrong about ConvertFunc.ahk not being included in v2converter.ahk (and using it indirectly). It is on line 155, so maybe just moving it to the top helped. The redundant entry on 155 can be deleted now.
