### ISSUE TITLE
Unneccessary trailing newlines in label conversion and at end of files

### ISSUE THREAD

**Issue by Banaanae** [mmikeww/AHK-v2-script-converter#193]
### This does not affect scripts abilities to run afaik
Unsure why this is happening, would be nice to get this fixed as it can cause a mess in scripts

Consider `Menu_ex7.ah1`'s conversion (in failing tests):
![image](https://github.com/mmikeww/AHK-v2-script-converter/assets/83927639/f85522e2-4929-4e88-b277-24a7787b8650)
It creates so many newlines that I can't even fit them all in the screenshot!
The causes seem pretty specific as well (but common enough where it happens in normal scripts)

For EOF example see `Menu_cbFunc_01.ah1`

**Comment by andymbody** [comment]
Yes, I agree... had this on my list to fix as well.

**Comment by andymbody** [comment]
Yes, I agree... had this on my list to fix as well. Do you want me to make this a priority and look into it since you're not well currently?

**Comment by andymbody** [comment]
Yes, I agree... had this on my list to fix as well. Its might be due to \s being used instead of \h in the regex needles. Do you want me to make this a priority and look into it since you're not well currently?

**Comment by andymbody** [comment]
Yes, I agree... had this on my list to fix as well. It might be due to \s being used instead of \h within the regex needles, since \s at the end of the needle could be capturing CRLF and adding one with each sub-convert. Do you want me to make this a priority and look into it since you're not well currently?

**Comment by andymbody** [comment]
Yes, I agree... had this on my list to fix as well. 

It might be due to \s being used instead of \h within the regex needles, since \s at the end of the needle could be capturing CRLF and adding one with each sub-convert. I changed \s to \h in a couple of the needles in my last PR. But I personally think they should all be changed just in case (unless warranted in rare cases). Processing line by line should theoretically not cause an issue in most cases, but there's no harm in changing this just to be specific and avoid hidden issues that are time consuming to track down. 

Do you want me to make this a priority and look into it since you're not well currently?

**Comment by andymbody** [comment]
Yes, I agree... had this on my radar to fix as well. 

Do you want me to make this a priority and look into it since you're not well currently?

**Comment by andymbody** [comment]
Yes, I agree... had this on my radar to fix as well. 

Do you want me to make this a priority and look into it since you are currently down-under the weather, down-under the world?

**Comment by andymbody** [comment]
Yes, I agree... had this on my radar to fix as well. I noticed it when I created Menu_cbFunc_01.ah1. I think it is in the _menu() func at least. Possibly others.

Also, although they shouldn't theoretically cause an issue with line by line processing, I think that the \s should be replaced with \h in the regex needles to avoid the possibility of hidden captures of CRLF. I think it's a good habit to be specific when the target should be restricted to a single line. This is my personal opinion and has saved unnecessary debugging for me in the past. 

Do you want me to make this a priority and look into it since you are currently down-under the weather, down-under the world? 😉

**Comment by andymbody** [comment]
Yes, I agree... had this on my radar to fix as well. I noticed it when I created Menu_cbFunc_01.ah1.

Traced it to the output of convertlabel2func().

The output needs to be trimmed of final CRLF. Added thus to return value which fixes it. 

Will submit a PR with this and update all the affected tests.

**Comment by andymbody** [comment]
Yes, I agree... had this on my radar to fix as well. I noticed it when I created Menu_cbFunc_01.ah1.

Traced it to the output of convertlabel2func().

The output needs to be trimmed of final CRLF. Added this trim to return value which fixes it. 

Will submit a PR with this fix and update all the affected tests.

**Comment by andymbody** [comment]
Yes, I agree... had this on my radar to fix as well. I noticed it when I created Menu_cbFunc_01.ah1.

Traced it to the output of convertlabel2func().

The output needs to be trimmed of final CRLF. Added this trim to return value which fixes it. 

Will submit a PR with this fix and update all the affected tests (when I get home from work this evening).
