### ISSUE TITLE
Better handling of removed directives?

### ISSUE THREAD

**Issue by Banaanae** [mmikeww/AHK-v2-script-converter#239]
V1:
```ahk
#CommentFlag NewString
#EscapeChar _

MsgBox, This is a test NewString should be omitted
MsgBox % "This is a _nnewline"
```

V2 (Converted):
```ahk
; REMOVED: #CommentFlag NewString
; REMOVED: #EscapeChar _

MsgBox("This is a test NewString should be omitted")
MsgBox("This is a _nnewline")
```

V2 (Expected):
```ahk
; REMOVED: #CommentFlag NewString
; REMOVED: #EscapeChar _

MsgBox("This is a test") ; should be omitted
MsgBox("This is a `nnewline")
```

**Comment by Banaanae** [comment]
Currently working on this

Updated test:
```ahk
#CommentFlag NewString
#EscapeChar _
#DerefChar #
#Delimiter /

Var = String

MsgBox/ This is a test NewString should be omitted
MsgBox # "This is a _nnewline"
MsgBox/ #Var#
```

**Comment by Banaanae** [comment]
How would it handle something like this?
```ahk
MsgBox, Test
#Delimiter -
MsgBox- Test
#Delimiter /
MsgBox/ Test
```
Current PR handles this

**Comment by andymbody** [comment]
> Current PR handles this

Gotcha... nice job :)

Btw... I found a bug in the masking. When I fixed it, it cause one of the onMessage tests to fail. Will be submitting a fix for that soon. I mention it because (similar to this) I think you warned me about the potential of breaking certain conversions when I first suggested masking. I hadn't run into any till now. Luckily there is only one (so far)... lol.

**Comment by Banaanae** [comment]
> When I fixed it, it cause one of the onMessage tests to fail.

Could it be failing because it's masking my mask? OnMessage conversion is very finicky  :)

> Luckily there is only one (so far)... lol.

If it has already lasted this long without too many major issues I doubt itll cause any now

**Comment by andymbody** [comment]
> Could it be failing because it's masking my mask? OnMessage conversion is very finicky :)

Lol... It is the one you masked, but my mask causes your code not to see the function, since it becomes a tag instead. I made a mistake in one of my edits that caused the masking not to return the masked version of code, so all was left exposed as normal code when it made it to _convertLines(). Without masking many more are broken than just the one, so will need to make an adjustment so all work correctly with masking turned on. I haven't had power for 4 days, and it might be another 2 weeks until I do. So, progress might be delayed.
