### ISSUE TITLE
Renaming of labels

### ISSUE THREAD

**Issue by dmtr99** [mmikeww/AHK-v2-script-converter#48]
I will add a function to rename the labels to the allowed characters.
if the first letter is a number, we will add _ before the label.
As this will be defined in a function, the rules can easily be changed.

[https://lexikos.github.io/v2/docs/misc/Labels.htm](https://lexikos.github.io/v2/docs/misc/Labels.htm)

**Comment by andymbody** [comment]
Does this still need to be addressed?

**Comment by Banaanae** [comment]
Yes see #201

**Comment by andymbody** [comment]
@dmtr99 added the function to replace number prefixes for labels. But that is all that was done. Will address the other characters as well.

Note: I did some research and testing and what I found was that characters for v1 label names are ridiculously non-restrictive. They can even begin with a semicolon! Should be fun designing a renaming convention that covers all cases, and yet not resulting in repeated replacement characters or killing the original description of the label. I will make it simple and we can adjust as needed from there.

I may need to replace the current related regex needles because they don't really cover all possible names that coders can come up with. I'm using the thousands of scripts in my library from other coders as a lab and you should see some of the unusual names and characters used for labels. I had no idea.

These are all valid labels in v1 (even a colon is allowed as part of the name)
#Persistent:
%A_Desktop%\List.txt:
c:\user\desktop\List.txt:

The only 3 things not allowed in v1 is whitespace, comma, and escape character. Everything else is fair game.
I'm glad v2 is more restrictive.

**Comment by andymbody** [comment]
@dmtr99 added the function to replace number prefixes for labels. But that is all that was done. Will address the other characters as well.

Note: I did some research and testing and what I found was that characters for v1 label names are ridiculously non-restrictive. They can even begin with a semicolon! Should be fun designing a renaming convention that covers all cases, and yet not resulting in repeated replacement characters or killing the original description of the label. I will make it simple and we can adjust as needed from there.

I may need to replace the current related regex needles because they don't really cover all possible names that coders can come up with. I'm using the thousands of scripts in my library from other coders as a lab and you should see some of the unusual names and characters used for labels. I had no idea.

These are all valid labels in v1 (even a colon is allowed as part of the name)
```
`;notACommetAnymore:		; begins with semicolon
:%A_Desktop%\List.txt: 		; begins with colon
c:\user\desktop\List.txt:	; has colon in middle of name
#Persistent:				; ahk directive
```

The only 3 things not allowed in v1 is whitespace, comma, and escape character. Everything else is fair game.
I'm glad v2 is more restrictive.

**Comment by andymbody** [comment]
@dmtr99 added the function to replace number prefixes for labels. But that is all that was done. Will address the other characters as well.

It will be fun... See comment here https://github.com/mmikeww/AHK-v2-script-converter/issues/201#issuecomment-2208048472
