### ISSUE TITLE
Adding to a Windows package manager scoop

### ISSUE THREAD

**Issue by eugenesvk** [mmikeww/AHK-v2-script-converter#52]
There is this great Windows package manager [scoop](https://scoop.sh) that simplifies installation of a lot of apps, especially cli-tools
I asked that they add your great converter (see this [request](https://github.com/ScoopInstaller/Extras/issues/7458)) now that AutoHotkey v2 is in beta (and it's included in scoop), though there is a reservation that it's too early as the converter is still WIP and it's best to wait till a stable release.
What do you think, would it make sense to add it or is it indeed too early?
(unfortunately, I've found your converter a bit too late after I've already converted my scripts, so don't know myself as to how ready it is)

**Comment by mmikeww** [comment]
I believe it is too early... converting AHK v1 to AHK v2 is a huge undertaking, since a lot of compatibility was broken, and some conversions are not even possible. I don't know if this converter will ever be officially "ready"... it was more designed simply as a helpful tool to allow users to quickly find the major syntax changes in order to save them A LOT of time.

BTW, how do you like scoop? I use chocolatey and it seems to work fine for me. And I heard Microsoft themselves released their own package manager. What does scoop do better/different?

**Comment by eugenesvk** [comment]
Ok, that's fine, then let the users find a "not yet ready" tool via forums and such

Haven't used Choco in ages, so can't properly compare it, but I love the non-admin install model of scoop and also consider the shim-instead-of-path model to be superior (and use their shims for a few of manually installed portable apps), if only it were more flexible and allow custom per-app install paths (the shims don't care, they can point to wherever)...

MS' winget isn't ready yet (can't even install stand-alone `.zip` apps) and they're not know to be builders of good app distribution models :), so don't have high hopes, but it's yet to be seen how good they can make it
