### ISSUE TITLE
v2converter.exe does not work

### ISSUE THREAD

**Issue by reinerblock** [mmikeww/AHK-v2-script-converter#63]
I tried multiple times to start the v2converter.exe and got always the same error message.

![grafik](https://user-images.githubusercontent.com/5745579/154543339-ef19fcd9-9519-4f52-98a8-6bc93c7ffc1d.png)

I even replaced the “…\AHK-v2-script-converter-master\AutoHotKey Exe\AutoHotkeyV2.exe” with the version of beta 3 and renamed it to have the same name.

**Comment by mmikeww** [comment]
The v2converter.exe file is simply a renamed AHK.exe interpreter. So you
can simply rename a beta3 exe file to v2converter and then replace the file

**Comment by reinerblock** [comment]
That's what I did.

**Comment by mmikeww** [comment]
I just tested it and it worked fine for me. If you used the file that you mentioned here:

> I even replaced the “…\AHK-v2-script-converter-master\AutoHotKey Exe\AutoHotkeyV2.exe” with the version of beta 3 and renamed it to have the same name.

Then that wouldn't work, since that file is beta1 also. You'd have to have downloaded beta3 from the AHK website and replaced that file.

Anyway, I've just pushed the changes to the repository so that the files are correct. So you can simply re-download the new changes now and it should work
