### ISSUE TITLE
Continuation section with Variables

### ISSUE THREAD

**Issue by dmtr99** [mmikeww/AHK-v2-script-converter#74]
The following script fails in conversion, gives errors and the wrong conversion.

```
	script =
	(
		document.querySelector('#userId').value = '%user%'
	
	)
```

This could be a correct conversion, but I hope V2 gets an cleaner solution in the future

```
	script := 
	(
		"document.querySelector('#userId').value = '" user "'"
	
	)
```

**Comment by Banaanae** [comment]
Variables now go from `%var%` to `" var "` in [51a52eb](https://github.com/mmikeww/AHK-v2-script-converter/commit/51a52ebf09b0947efa56bc2b82156f175defe1dd)


Still need to make
```ahk
var := "
(
    Content
)"
```
to
```ahk
var := 
(
    "Content"
)
```

**Comment by andymbody** [comment]
> The following script fails in conversion, gives errors and the wrong conversion.
> 
> ```
> 	script =
> 	(
> 		document.querySelector('#userId').value = '%user%'
> 	
> 	)
> ```

This gives errors in v1 (doesn't like the apostrophe chars). Should it be considered something that needs to be converted correctly even tho the v1 code produces errors to begin with?

**Comment by andymbody** [comment]
> ```ahk
> var := "
> (
>     Content
> )"
> ```

Why does this need converted? The docs show it as legit.

**Comment by andymbody** [comment]
How should this look afterwards?

I converted this...
```
user := "defaultuser0"
script =
(
	document.querySelector('#userId').value = '%user%'
)
MsgBox % script
```
... to this...

```
user := "defaultuser0"
script := 
(
	"document.querySelector('#userId').value = '" user "'"
)
MsgBox(script)
```

But this broke other tests within the test suite. For instance... this is now broken, but looks to be the same structure as above. But the expected for it has quotes outside the parentheses, rather than inside.

```
var =
(
line1
line2
)
```

There seems to be some inconsistency regarding expected outcome. Which should be expected... quotes inside the parentheses, or outside?

Thanks

**Comment by andymbody** [comment]
Clarification needed before continuing with this fix...

How should this look afterwards?

I converted this...
```
user := "defaultuser0"
script =
(
	document.querySelector('#userId').value = '%user%'
)
MsgBox % script
```
... to this...

```
user := "defaultuser0"
script := 
(
	"document.querySelector('#userId').value = '" user "'"
)
MsgBox(script)
```

But this broke other tests within the test suite. For instance... this is now broken, but looks to be the same structure as above. But the expected for it has quotes outside the parentheses, rather than inside.

```
var =
(
line1
line2
)
```

There seems to be some inconsistency regarding expected outcome. Which should be expected... quotes inside the parentheses, or outside?

With quotes outside, the CRLF and whitespace are preserved as written. But with quotes inside, some of this is lost. I would expect that the whitespace is a priority with multiline strings and should be preserved. This would require quotes on outside of block. I think the output needs to stay consistent with the way it was written (originally intended by the author), Otherwise the author could have simply used normal string formatting rather than a multiline string, right?

Without consistency we will be writing a different conversion algorithm for every unique string that is encountered. I think this would be overkill and not very productive.

Thanks

**Comment by andymbody** [comment]
> Variables now go from `%var%` to `" var "` in [51a52eb](https://github.com/mmikeww/AHK-v2-script-converter/commit/51a52ebf09b0947efa56bc2b82156f175defe1dd)
> 
> Still need to make
> 
> ```ahk
> var := "
> (
>     Content
> )"
> ```
> 
> to
> 
> ```ahk
> var := 
> (
>     "Content"
> )
> ```

Both of these are valid multiline string formats. What is the criteria for deciding whether quotes are place inside or outside the parentheses?

**Comment by Banaanae** [comment]
V1 - Output: This is a Test
```ahk
MyVar = Test

MySection =
(
	This is a %MyVar%
)

MsgBox % MySection
```
V2 (Converted) - Output: This is a " MyVar "
MyVar := "Test"

MySection := "
(
	This is a " MyVar "
)"

MsgBox(MySection)
```
V2 (Expected) - Output: This is a Test
```ahk
MyVar := "Test"

MySection := 
(
	"This is a " MyVar ""
)

MsgBox(MySection)
```
